apiVersion: v1
kind: Service
metadata:
  name: {{ include "reddit-rss.fullname" . }}
  labels: {{- include "reddit-rss.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector: {{- include "reddit-rss.selectorLabels" . | nindent 4 }}
